/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(5), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(6), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(6), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(6), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(6), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(6), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(6), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(7), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(7), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(8), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(8), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(9), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(9), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(10), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(10), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(10), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(10), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(10), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(10), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(10), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(11), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(11), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(12), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(12), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(12), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(13), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(13), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(13), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(13), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(13), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(14), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(14), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(15), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(15), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(15), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(15), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(15), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(15), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(15), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(15), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(15), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(15), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(16), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(17), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(17), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(18), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(18), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(19), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(20), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(20), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(20), list);
		    }
		    break;


                    case 83:
		    {
			ArrayList list = new83();
			push(goTo(20), list);
		    }
		    break;


                    case 84:
		    {
			ArrayList list = new84();
			push(goTo(21), list);
		    }
		    break;


                    case 85:
		    {
			ArrayList list = new85();
			push(goTo(21), list);
		    }
		    break;


                    case 86:
		    {
			ArrayList list = new86();
			push(goTo(22), list);
		    }
		    break;


                    case 87:
		    {
			ArrayList list = new87();
			push(goTo(22), list);
		    }
		    break;


                    case 88:
		    {
			ArrayList list = new88();
			push(goTo(23), list);
		    }
		    break;


                    case 89:
		    {
			ArrayList list = new89();
			push(goTo(23), list);
		    }
		    break;


                    case 90:
		    {
			ArrayList list = new90();
			push(goTo(24), list);
		    }
		    break;


                    case 91:
		    {
			ArrayList list = new91();
			push(goTo(24), list);
		    }
		    break;


                    case 92:
		    {
			ArrayList list = new92();
			push(goTo(25), list);
		    }
		    break;


                    case 93:
		    {
			ArrayList list = new93();
			push(goTo(25), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new AGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new AGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFunctionCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatementCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFunction(tidNode2, null, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        PArgument pargumentNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunction(tidNode2, pargumentNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AArgument(tidNode2, null, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PSetValue psetvalueNode3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        psetvalueNode3 = (PSetValue)nodeArrayList2.get(0);
        {
        }

        pargumentNode1 = new AArgument(tidNode2, psetvalueNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, null, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PSetValue psetvalueNode3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        psetvalueNode3 = (PSetValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgument(tidNode2, psetvalueNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PSetValue psetvalueNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        psetvalueNode1 = new ASetValue(pvalueNode2);
        }
	nodeList.add(psetvalueNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PNextArg pnextargNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pnextargNode1 = new ANextArg(tidNode2, null);
        }
	nodeList.add(pnextargNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PNextArg pnextargNode1;
        {
        TId tidNode2;
        PSetValue psetvalueNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        psetvalueNode3 = (PSetValue)nodeArrayList3.get(0);

        pnextargNode1 = new ANextArg(tidNode2, psetvalueNode3);
        }
	nodeList.add(pnextargNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList3.get(0);
        tidNode3 = (TId)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AMinEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AMinEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ADivEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new ADivEqualStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AArrayEqualStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AArrayEqualStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        Object nullNode3 = null;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PNextExpression pnextexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        pnextexpressionNode3 = (PNextExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pnextexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        PNextExpression pnextexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pnextexpressionNode3 = (PNextExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssertStatement(pexpressionNode2, pnextexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFunctionCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFunctionCallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);

        pcomparisonNode1 = new ANotComparison(pcomparisonNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AAndComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        PComparison pcomparisonNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        pcomparisonNode3 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new AOrComparison(pcomparisonNode2, pcomparisonNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreaterComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALessComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqualsComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreaterOrEqualComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALessOrEqualComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANotEqualsComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pcomparisonNode1 = new ATrueComparison(ttrueNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pcomparisonNode1 = new AFalseComparison(tfalseNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new APlusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AModExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADmultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdentExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArrayIdExpression(tidNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFunctionCallExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList5.get(0);

        pexpressionNode1 = new AOpenExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList3.get(0);

        pexpressionNode1 = new ATypeExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMaxExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMinExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AArrayExpExpression(pexpressionNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AArrayExpExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PNextExpression pnextexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pnextexpressionNode1 = new ANextNextExpression(pexpressionNode2);
        }
	nodeList.add(pnextexpressionNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pfunctioncallNode1 = new AFunctionCallFunctionCall(tidNode2, null);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        PArglist parglistNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        parglistNode3 = (PArglist)nodeArrayList3.get(0);

        pfunctioncallNode1 = new AFunctionCallFunctionCall(tidNode2, parglistNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArglist parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArglist(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreValues pmorevaluesNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pmorevaluesNode1 = new AMoreMoreValues(pvalueNode2);
        }
	nodeList.add(pmorevaluesNode1);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TId tidNode2;
        TFullstop tfullstopNode3;
        PFunctionCall pfunctioncallNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tfullstopNode3 = (TFullstop)nodeArrayList2.get(0);
        pfunctioncallNode4 = (PFunctionCall)nodeArrayList3.get(0);

        pvalueNode1 = new AIdValue(tidNode2, tfullstopNode3, pfunctioncallNode4);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(tnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new83()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TNull tnullNode2;
        tnullNode2 = (TNull)nodeArrayList1.get(0);

        pvalueNode1 = new ANoneValue(tnullNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new84()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new85()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new86()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PNextArg pnextargNode1;
        pnextargNode1 = (PNextArg)nodeArrayList1.get(0);
	if(pnextargNode1 != null)
	{
	  listNode2.add(pnextargNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new87()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PNextArg pnextargNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pnextargNode2 = (PNextArg)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pnextargNode2 != null)
	{
	  listNode3.add(pnextargNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new88()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new89()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new90()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PNextExpression pnextexpressionNode1;
        pnextexpressionNode1 = (PNextExpression)nodeArrayList1.get(0);
	if(pnextexpressionNode1 != null)
	{
	  listNode2.add(pnextexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new91()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PNextExpression pnextexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pnextexpressionNode2 = (PNextExpression)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pnextexpressionNode2 != null)
	{
	  listNode3.add(pnextexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new92()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreValues pmorevaluesNode1;
        pmorevaluesNode1 = (PMoreValues)nodeArrayList1.get(0);
	if(pmorevaluesNode1 != null)
	{
	  listNode2.add(pmorevaluesNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new93()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreValues pmorevaluesNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmorevaluesNode2 = (PMoreValues)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmorevaluesNode2 != null)
	{
	  listNode3.add(pmorevaluesNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {1, SHIFT, 2}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, REDUCE, 88}, },
			{{-1, ERROR, 2}, {41, SHIFT, 17}, },
			{{-1, ERROR, 3}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {31, SHIFT, 24}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 4}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {31, SHIFT, 24}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 5}, {41, SHIFT, 43}, },
			{{-1, ERROR, 6}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 7}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 8}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 9}, {2, SHIFT, 47}, {13, SHIFT, 48}, {14, SHIFT, 49}, {15, SHIFT, 50}, {16, SHIFT, 51}, },
			{{-1, ERROR, 10}, {44, ACCEPT, -1}, },
			{{-1, REDUCE, 84}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {1, SHIFT, 2}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 16}, {0, SHIFT, 53}, {6, SHIFT, 54}, {8, SHIFT, 55}, {9, SHIFT, 56}, {11, SHIFT, 57}, {12, SHIFT, 58}, {18, SHIFT, 59}, {41, SHIFT, 60}, },
			{{-1, ERROR, 17}, {2, SHIFT, 62}, },
			{{-1, ERROR, 18}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 19}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 20}, {2, SHIFT, 65}, },
			{{-1, ERROR, 21}, {2, SHIFT, 66}, },
			{{-1, ERROR, 22}, {2, SHIFT, 67}, },
			{{-1, ERROR, 23}, {2, SHIFT, 68}, },
			{{-1, ERROR, 24}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 83}, },
			{{-1, REDUCE, 62}, {2, SHIFT, 47}, {7, SHIFT, 70}, {16, SHIFT, 71}, },
			{{-1, REDUCE, 82}, },
			{{-1, REDUCE, 81}, },
			{{-1, ERROR, 31}, {4, SHIFT, 72}, },
			{{-1, REDUCE, 39}, {29, SHIFT, 73}, },
			{{-1, REDUCE, 41}, {30, SHIFT, 74}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 36}, {19, SHIFT, 75}, {20, SHIFT, 76}, {32, SHIFT, 77}, {33, SHIFT, 78}, {34, SHIFT, 79}, {35, SHIFT, 80}, {38, SHIFT, 81}, {39, SHIFT, 82}, },
			{{-1, REDUCE, 54}, {21, SHIFT, 83}, {22, SHIFT, 84}, {23, SHIFT, 85}, {24, SHIFT, 86}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 42}, {4, SHIFT, 87}, },
			{{-1, ERROR, 43}, {10, SHIFT, 88}, },
			{{-1, REDUCE, 19}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 21}, {5, SHIFT, 89}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 33}, {5, SHIFT, 89}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 47}, {2, SHIFT, 18}, {3, SHIFT, 93}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 48}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 49}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 50}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 51}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 85}, },
			{{-1, REDUCE, 89}, },
			{{-1, ERROR, 54}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {31, SHIFT, 24}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 55}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {31, SHIFT, 24}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 56}, {41, SHIFT, 102}, },
			{{-1, ERROR, 57}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 58}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 59}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 60}, {2, SHIFT, 47}, {13, SHIFT, 106}, {14, SHIFT, 107}, {15, SHIFT, 108}, {16, SHIFT, 109}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 62}, {3, SHIFT, 110}, {41, SHIFT, 111}, },
			{{-1, ERROR, 63}, {3, SHIFT, 113}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 64}, {5, SHIFT, 89}, {17, SHIFT, 114}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 65}, {40, SHIFT, 27}, {41, SHIFT, 116}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 66}, {40, SHIFT, 27}, {41, SHIFT, 116}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 67}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 68}, {41, SHIFT, 120}, },
			{{-1, REDUCE, 40}, {29, SHIFT, 73}, },
			{{-1, ERROR, 70}, {41, SHIFT, 121}, },
			{{-1, ERROR, 71}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 72}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 73}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 74}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {36, SHIFT, 25}, {37, SHIFT, 26}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 75}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 76}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 77}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 78}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 79}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 80}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 81}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 82}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 83}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 84}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 85}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 86}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 87}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 88}, {41, SHIFT, 140}, },
			{{-1, ERROR, 89}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 90}, },
			{{-1, REDUCE, 23}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 77}, {5, SHIFT, 89}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 95}, {3, SHIFT, 144}, },
			{{-1, REDUCE, 25}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 27}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 29}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 99}, {17, SHIFT, 145}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 100}, {4, SHIFT, 146}, },
			{{-1, ERROR, 101}, {4, SHIFT, 147}, },
			{{-1, ERROR, 102}, {10, SHIFT, 148}, },
			{{-1, REDUCE, 20}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 22}, {5, SHIFT, 89}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 34}, {5, SHIFT, 89}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 106}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 107}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 108}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 109}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, ERROR, 110}, {4, SHIFT, 155}, },
			{{-1, REDUCE, 6}, {5, SHIFT, 156}, {13, SHIFT, 157}, },
			{{-1, ERROR, 112}, {3, SHIFT, 161}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 115}, {5, SHIFT, 89}, {17, SHIFT, 162}, },
			{{-1, ERROR, 116}, {7, SHIFT, 70}, },
			{{-1, ERROR, 117}, {5, SHIFT, 163}, },
			{{-1, ERROR, 118}, {5, SHIFT, 163}, },
			{{-1, ERROR, 119}, {5, SHIFT, 167}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 120}, {3, SHIFT, 168}, },
			{{-1, ERROR, 121}, {2, SHIFT, 47}, },
			{{-1, REDUCE, 80}, },
			{{-1, ERROR, 123}, {17, SHIFT, 169}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 42}, {30, SHIFT, 74}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 55}, {21, SHIFT, 83}, {22, SHIFT, 84}, {23, SHIFT, 85}, {24, SHIFT, 86}, },
			{{-1, REDUCE, 56}, {21, SHIFT, 83}, {22, SHIFT, 84}, {23, SHIFT, 85}, {24, SHIFT, 86}, },
			{{-1, REDUCE, 47}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 46}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 51}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 48}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 49}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 50}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 140}, {4, SHIFT, 170}, },
			{{-1, REDUCE, 74}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 91}, },
			{{-1, REDUCE, 78}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 76}, },
			{{-1, ERROR, 145}, {13, SHIFT, 171}, },
			{{-1, ERROR, 146}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 147}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 148}, {41, SHIFT, 174}, },
			{{-1, REDUCE, 24}, {5, SHIFT, 89}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 26}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 28}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 30}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 154}, {17, SHIFT, 175}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 155}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 156}, {41, SHIFT, 177}, },
			{{-1, ERROR, 157}, {40, SHIFT, 27}, {41, SHIFT, 116}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 7}, {5, SHIFT, 156}, },
			{{-1, REDUCE, 86}, },
			{{-1, REDUCE, 8}, {5, SHIFT, 156}, },
			{{-1, ERROR, 161}, {4, SHIFT, 181}, },
			{{-1, REDUCE, 73}, },
			{{-1, ERROR, 163}, {40, SHIFT, 27}, {41, SHIFT, 116}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 92}, },
			{{-1, ERROR, 165}, {3, SHIFT, 183}, {5, SHIFT, 163}, },
			{{-1, ERROR, 166}, {3, SHIFT, 185}, {5, SHIFT, 163}, },
			{{-1, ERROR, 167}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 68}, },
			{{-1, REDUCE, 63}, },
			{{-1, ERROR, 170}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 171}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 174}, {4, SHIFT, 189}, },
			{{-1, ERROR, 175}, {13, SHIFT, 190}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 11}, {13, SHIFT, 157}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 9}, {5, SHIFT, 156}, },
			{{-1, REDUCE, 87}, },
			{{-1, ERROR, 181}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, REDUCE, 79}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 93}, },
			{{-1, REDUCE, 70}, },
			{{-1, ERROR, 186}, {3, SHIFT, 193}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 31}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
			{{-1, ERROR, 189}, {0, SHIFT, 1}, {6, SHIFT, 3}, {8, SHIFT, 4}, {9, SHIFT, 5}, {11, SHIFT, 6}, {12, SHIFT, 7}, {18, SHIFT, 8}, {41, SHIFT, 9}, },
			{{-1, ERROR, 190}, {2, SHIFT, 18}, {16, SHIFT, 19}, {25, SHIFT, 20}, {26, SHIFT, 21}, {27, SHIFT, 22}, {28, SHIFT, 23}, {40, SHIFT, 27}, {41, SHIFT, 28}, {42, SHIFT, 29}, {43, SHIFT, 30}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 32}, {19, SHIFT, 75}, {20, SHIFT, 76}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {15, 52}, },
			{{-1, 12}, },
			{{-1, 112}, },
			{{-1, 158}, {177, 191}, },
			{{-1, 159}, {160, 180}, {179, 180}, },
			{{-1, 13}, {72, 124}, {87, 139}, {146, 172}, {147, 173}, {155, 176}, {170, 187}, {181, 192}, {189, 194}, },
			{{-1, 31}, {4, 42}, {54, 100}, {55, 101}, },
			{{-1, 32}, {24, 69}, },
			{{-1, 33}, {73, 125}, },
			{{-1, 34}, {74, 126}, },
			{{-1, 35}, },
			{{-1, 36}, {6, 44}, {7, 45}, {8, 46}, {18, 63}, {19, 64}, {47, 94}, {48, 96}, {49, 97}, {50, 98}, {51, 99}, {57, 103}, {58, 104}, {59, 105}, {67, 119}, {71, 123}, {77, 129}, {78, 130}, {79, 131}, {80, 132}, {81, 133}, {82, 134}, {89, 141}, {106, 151}, {107, 152}, {108, 153}, {109, 154}, {167, 186}, {171, 188}, {190, 195}, },
			{{-1, 37}, {75, 127}, {76, 128}, },
			{{-1, 38}, },
			{{-1, 39}, {83, 135}, {84, 136}, {85, 137}, {86, 138}, },
			{{-1, 90}, {46, 92}, {91, 142}, {105, 150}, {115, 142}, {143, 142}, {149, 142}, },
			{{-1, 40}, {0, 14}, {15, 14}, {16, 61}, {70, 122}, {72, 14}, {87, 14}, {146, 14}, {147, 14}, {155, 14}, {170, 14}, {181, 14}, {189, 14}, },
			{{-1, 95}, },
			{{-1, 164}, {165, 184}, {166, 184}, },
			{{-1, 41}, {65, 117}, {66, 118}, {157, 178}, {163, 182}, },
			{{-1, 15}, },
			{{-1, 160}, {158, 179}, },
			{{-1, 16}, },
			{{-1, 91}, {64, 115}, {94, 143}, {104, 149}, },
			{{-1, 165}, {118, 166}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'for', 'return', 'print', 'assert', id, EOF",
			"expecting: tab, 'if', 'while', 'for', 'return', 'print', 'assert', id",
			"expecting: id",
			"expecting: '(', '[', 'max', 'min', 'open', 'type', 'not', 'true', 'false', 'None', id, string, number",
			"expecting: '(', '[', 'max', 'min', 'open', 'type', 'None', id, string, number",
			"expecting: '(', '=', '-=', '/=', '['",
			"expecting: EOF",
			"expecting: '('",
			"expecting: '(', '[', 'max', 'min', 'open', 'type', 'true', 'false', 'None', id, string, number",
			"expecting: ':', 'and', 'or'",
			"expecting: tab, 'def', ')', ':', ',', 'if', 'while', 'for', 'return', 'print', ']', 'assert', '+', '-', '*', '**', '/', '%', 'and', 'or', '<', '>', '!=', '==', '=>', '<=', id, EOF",
			"expecting: tab, 'def', '(', ')', ':', ',', 'if', '.', 'while', 'for', 'return', 'print', '[', ']', 'assert', '+', '-', '*', '**', '/', '%', 'and', 'or', '<', '>', '!=', '==', '=>', '<=', id, EOF",
			"expecting: ':'",
			"expecting: ':', 'and'",
			"expecting: '+', '-', '<', '>', '!=', '==', '=>', '<='",
			"expecting: 'in'",
			"expecting: tab, 'def', 'if', 'while', 'for', 'return', 'print', 'assert', '+', '-', id, EOF",
			"expecting: tab, 'def', ',', 'if', 'while', 'for', 'return', 'print', 'assert', '+', '-', id, EOF",
			"expecting: '(', ')', '[', 'max', 'min', 'open', 'type', 'None', id, string, number",
			"expecting: ')', id",
			"expecting: ')', '+', '-'",
			"expecting: ',', ']', '+', '-'",
			"expecting: 'None', id, string, number",
			"expecting: tab, 'def', ')', ',', 'if', 'while', 'for', 'return', 'print', ']', 'assert', id, EOF",
			"expecting: tab, 'def', ',', 'if', 'while', 'for', 'return', 'print', 'assert', id, EOF",
			"expecting: ')', ',', '+', '-'",
			"expecting: ')'",
			"expecting: ']', '+', '-'",
			"expecting: ')', ',', '='",
			"expecting: ',', ']'",
			"expecting: '.'",
			"expecting: ','",
			"expecting: ',', '+', '-'",
			"expecting: ':', '+', '-', 'and', 'or'",
			"expecting: tab, 'def', ')', ',', 'if', 'while', 'for', 'return', 'print', ']', 'assert', '+', '-', id, EOF",
			"expecting: ')', ','",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 2, 4, 4, 4, 5, 6, 0, 0, 0, 0, 0, 1, 7, 4, 4, 7, 7, 7, 7, 8, 9, 9, 10, 11, 10, 10, 12, 13, 9, 9, 9, 14, 10, 10, 10, 10, 10, 12, 15, 16, 17, 17, 18, 4, 4, 4, 4, 0, 1, 3, 3, 2, 4, 4, 4, 5, 0, 19, 20, 21, 22, 22, 4, 2, 13, 2, 4, 1, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 2, 4, 23, 24, 0, 10, 25, 26, 16, 16, 16, 27, 12, 12, 15, 16, 17, 17, 4, 4, 4, 4, 12, 28, 26, 10, 10, 29, 30, 31, 31, 32, 26, 7, 10, 27, 0, 9, 9, 10, 10, 33, 33, 33, 33, 33, 33, 10, 10, 10, 10, 0, 12, 34, 23, 35, 10, 36, 1, 1, 2, 24, 0, 16, 16, 16, 27, 1, 2, 22, 35, 35, 35, 12, 10, 22, 35, 35, 35, 4, 10, 10, 1, 4, 0, 0, 12, 36, 0, 28, 35, 35, 35, 1, 35, 10, 35, 10, 20, 0, 16, 1, 4, 35, 0, 10, 0, 16, 
        };*/
}
