/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArgument extends PArgument
{
    private TId _id_;
    private PSetValue _setValue_;
    private final LinkedList _nextArg_ = new TypedLinkedList(new NextArg_Cast());

    public AArgument()
    {
    }

    public AArgument(
        TId _id_,
        PSetValue _setValue_,
        List _nextArg_)
    {
        setId(_id_);

        setSetValue(_setValue_);

        {
            this._nextArg_.clear();
            this._nextArg_.addAll(_nextArg_);
        }

    }
    public Object clone()
    {
        return new AArgument(
            (TId) cloneNode(_id_),
            (PSetValue) cloneNode(_setValue_),
            cloneList(_nextArg_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgument(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PSetValue getSetValue()
    {
        return _setValue_;
    }

    public void setSetValue(PSetValue node)
    {
        if(_setValue_ != null)
        {
            _setValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _setValue_ = node;
    }

    public LinkedList getNextArg()
    {
        return _nextArg_;
    }

    public void setNextArg(List list)
    {
        _nextArg_.clear();
        _nextArg_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_setValue_)
            + toString(_nextArg_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_setValue_ == child)
        {
            _setValue_ = null;
            return;
        }

        if(_nextArg_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_setValue_ == oldChild)
        {
            setSetValue((PSetValue) newChild);
            return;
        }

        for(ListIterator i = _nextArg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class NextArg_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PNextArg node = (PNextArg) o;

            if((node.parent() != null) &&
                (node.parent() != AArgument.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArgument.this))
            {
                node.parent(AArgument.this);
            }

            return node;
        }
    }
}
