/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAssertStatement extends PStatement
{
    private PExpression _expression_;
    private PNextExpression _nextExpression_;

    public AAssertStatement()
    {
    }

    public AAssertStatement(
        PExpression _expression_,
        PNextExpression _nextExpression_)
    {
        setExpression(_expression_);

        setNextExpression(_nextExpression_);

    }
    public Object clone()
    {
        return new AAssertStatement(
            (PExpression) cloneNode(_expression_),
            (PNextExpression) cloneNode(_nextExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssertStatement(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public PNextExpression getNextExpression()
    {
        return _nextExpression_;
    }

    public void setNextExpression(PNextExpression node)
    {
        if(_nextExpression_ != null)
        {
            _nextExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _nextExpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_nextExpression_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_nextExpression_ == child)
        {
            _nextExpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(_nextExpression_ == oldChild)
        {
            setNextExpression((PNextExpression) newChild);
            return;
        }

    }
}
