/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANextArg extends PNextArg
{
    private TId _id_;
    private PSetValue _setValue_;

    public ANextArg()
    {
    }

    public ANextArg(
        TId _id_,
        PSetValue _setValue_)
    {
        setId(_id_);

        setSetValue(_setValue_);

    }
    public Object clone()
    {
        return new ANextArg(
            (TId) cloneNode(_id_),
            (PSetValue) cloneNode(_setValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextArg(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PSetValue getSetValue()
    {
        return _setValue_;
    }

    public void setSetValue(PSetValue node)
    {
        if(_setValue_ != null)
        {
            _setValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _setValue_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_setValue_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_setValue_ == child)
        {
            _setValue_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_setValue_ == oldChild)
        {
            setSetValue((PSetValue) newChild);
            return;
        }

    }
}
