/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TFastSub extends Token
{
    public TFastSub()
    {
        super.setText("-=");
    }

    public TFastSub(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFastSub(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFastSub(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TFastSub text.");
    }
}
