/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGreaterOrEqual extends Token
{
    public TGreaterOrEqual()
    {
        super.setText("=>");
    }

    public TGreaterOrEqual(int line, int pos)
    {
        super.setText("=>");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreaterOrEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreaterOrEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreaterOrEqual text.");
    }
}
