/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLeftBracket extends Token
{
    public TLeftBracket()
    {
        super.setText("[");
    }

    public TLeftBracket(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLeftBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeftBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLeftBracket text.");
    }
}
