/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TRightBracket extends Token
{
    public TRightBracket()
    {
        super.setText("]");
    }

    public TRightBracket(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRightBracket(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRightBracket(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRightBracket text.");
    }
}
