/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSet extends Token
{
    public TSet()
    {
        super.setText("=");
    }

    public TSet(int line, int pos)
    {
        super.setText("=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSet(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSet(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSet text.");
    }
}
